general.import = [
   "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }

[window]
padding.x = 10
padding.y = 10
dimensions = {columns = 150, lines = 40}

decorations = "Buttonless"

opacity = 0.9
blur = true

option_as_alt = "Both"
